app:
    resource: "@AdittionBundle/Controller/"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
contact:
    path: /contact
    defaults: { _controller: AppBundle:Main:contact}

# src/Acme/DemoBundle/Resources/config/routing.yml:
randomize:
    path: /rand/{limit}
    defaults: { _controller: AppBundle:Main:randomize}


# src/AdittionBundle/Resources/config/routing.yml:
add:
    path: /add/{a}-{b}
    defaults: { _controller: AdittionBundle:Adittion:add}

hello:
    path: /hello
    defaults: { _controller: AdittionBundle:Adittion:hello}

name:
    path: /insertname/{name}
    defaults: { _controller: AdittionBundle:Adittion:name}

# app/config/routing.yml
welcome:
    path: /
    defaults: { _controller: AppBundle:Welcome:index}

# app/config/routing.yml
article_show:
     path: /article/{slug}
     defaults: { _controller: AppBundle:Article:show}

# src/AppBundle/DefaultController
create_entry:
     path: /create
     defaults: { _controller: AppBundle:Default:create}

# src/AppBundle/DefultController and view app/Resources/views/dbactions
show_entry:
     path: /show/{id}
     defaults: { _controller: AppBundle:Default:show}

# src/AppBundle/Entity/Product
datetime_callback:
     path: /created
     defaults: { _controller: AppBundle:Default:createdAt}

# src/AppBundle/Controller/Default/authorAction
validation:
    path: /isvalid
    defaults: { _controller: AppBundle:Default:author}

