# app/config/security.yml

security:
    providers:
      in_memory:
          memory:
              users:
                  dan:
                      password: $2a$12$RiwsfQ1lgWi2nVkxAZHJM.1x5RK59am1iHbSYZcHNJzzBL92fFTKe #string
                      roles: 'ROLE_USER'
                  admin:
                      password: $2a$12$XV5flOQMMBCH1DMaQpVGGuPwCZzEF/M9OZtX2eO0hMuR5dXRW7zDO #111111
                      roles: 'ROLE_ADMIN'

    encoders:
      Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            http_basic: ~

    access_control:
            - { path: ^/admin/users, roles: ROLE_SUPER_ADMIN }
            - { path: ^/admin, roles: ROLE_ADMIN }
